#!/bin/sh
green='\e[0;32m'
yellow='\e[0;33m'
white='\e[0;37m'

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

if [ ! -e /usr/bin/osso ]; then
    cp osso /usr/bin/osso
fi

echo -e "${white}***********************************************"
echo -e "        ${green}Osso ${yellow}successfully installed${white}"
echo -e "***********************************************"
