#!/bin/sh
green='\e[0;32m'
yellow='\e[0;33m'
white='\e[0;37m'

if [[ $EUID -ne 0 ]]; then
    echo -e "${green}This script must be run as ${yellow}root${white}" 1>&2
   exit 1
fi

if [ -e /usr/bin/osso ]; then
    rm /usr/bin/osso
fi

if [ -e /usr/share/applications/osso.desktop ]; then
    rm /usr/share/applications/osso.desktop
fi

if [ -e /usr/share/pixmaps/osso.png ]; then
    rm /usr/share/pixmaps/osso.png
fi

echo -e "${white}***********************************************"
echo -e "        ${green}Osso ${yellow}successfully uninstalled${white}"
echo -e "***********************************************"
