#!/bin/sh
green='\e[0;32m'
yellow='\e[0;33m'
white='\e[0;37m'

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

if [ -f /usr/bin/osso ]; then
    rm /usr/bin/osso
fi

echo -e "${white}***********************************************"
echo -e "        ${green}Osso ${yellow}successfully uninstalled${white}"
echo -e "***********************************************"
